### ISSUE TITLE
Is Postgres full-text search as flexible and easy to implement as Elasticsearch in a Rails app?

### ISSUE THREAD

**Issue by monfresh** [codeforamerica/ohana-api#139]
Postgres also has full-text search capabilities (which we haven't researched yet), and we hope it will be able to provide the same functionality as Elasticsearch. If that's the case, it will allow us to remove another dependency.

**Comment by ylluminate** [comment]
How's this looking as of April 2015?  Any updates or performance improvements?  I've been considering using [`pg_search`](https://github.com/Casecommons/pg_search) to simplify an ElasticSearch nightmare we've been having.

**Comment by monfresh** [comment]
It's been working great. We've been using pg_search in production (Heroku) for several months without any issues.

**Comment by ylluminate** [comment]
@monfresh :+1: thanks for the feedback.  Certainly would like more benchmark info, but honestly the headaches we've had with ElasticSearch likely will be outweighed even if this is just a little slower.

**Comment by monfresh** [comment]
I don't have benchmark comparisons for you unfortunately, and your numbers will depend on how you configure your server, how much traffic you get, and what kind of caching you implement. What I can tell you is that our Heroku server gets between 20,000 and 50,000 requests per week (they don't all hit the DB), and our database response time averages under 15ms, and the app response time has been between 40ms and 80ms on average according to New Relic.

**Comment by orlando** [comment]
@monfresh this is a great write up. Did you made a post out of this thread?.

**Comment by monfresh** [comment]
@orlando I did not, but that's a good idea.

**Comment by thebenedict** [comment]
@monfresh This is exactly the information I was looking for and couldn't find in the pg_search docs or other blog posts. Well worth making a post if you have the time. Thank you for the thorough work and having this discussion in a public thread.
