### ISSUE TITLE
RFC: using the Pundit gem

### ISSUE THREAD

**Issue by volkanunsal** [codeforamerica/ohana-api#215]
I love you guys for building this API. I used it heavily for my project Edori. Thanks for all you are doing. 

There are a few suggestions I wanted to make about stuff that would be useful to help you guys achieve your goals. For my own implementation, I found the [Pundit gem](https://github.com/elabs/pundit) much more flexible for managing authorizations. This gem is similar to the approach you guys are already taking with using Decorators. It's nothing more than a decorator with a few fancy tricks up its sleeve. I wanted to open a discussion about that since it may be a judgment call. (In fact, there are a few suggestions I want to make, so be warned.)

I can send a pull request from my implementation if Pundit might be interesting to you. :)

**Comment by monfresh** [comment]
Just adding a note for historical purposes that this was implemented in 5eea5dea27fa418bdc522b213437bde0346d55f9
