### ISSUE TITLE
Generate CSV files from a Google Docs spreadsheet

### ISSUE THREAD

**Issue by pmackay** [codeforamerica/ohana-api#281]
Is there any tool or guidance on creating a set of CSV files from a GDocs spreadsheet such as the suggested template?

https://docs.google.com/spreadsheets/d/1qkysLj5MAAvaysuac_9H0hOvTAb1aJEMhUVJAECmj2c/edit#gid=595985385

**Comment by monfresh** [comment]
I've updated the Wiki article with more detailed instructions. Closing this now. Thanks for this contribution!
Here's the updated article: https://github.com/codeforamerica/ohana-api/wiki/Automatically-generate-CSV-files-from-an-OpenReferral-Google-spreadsheet
