### ISSUE TITLE
"No implicit conversion from true" error in application.yml during deployment

### ISSUE THREAD

**Issue by volkanunsal** [codeforamerica/ohana-api#302]
It's coming from this line:

```yml
ENABLE_HTTPS: yes
```

**Comment by monfresh** [comment]
Can you please be more specific? What are the exact steps to reproduce this issue? Is this with your Heroku deployment code, or when following the instructions in this repo with the current code in the master branch?

**Comment by volkanunsal** [comment]
It happens when I run the deployment script, not from app.json deployment. You just create an app and run setup_heroku. I quoted `yes` to `'yes'` make it work.

**Comment by monfresh** [comment]
Good catch, thanks! I just fixed it, along with some other issues with the script.

https://github.com/codeforamerica/ohana-api/commit/0eaadca367ee4e5fad229998a979c6692dc59b3d
