### ISSUE TITLE
/api and /admin routes are missing after app.json deployment

### ISSUE THREAD

**Issue by volkanunsal** [codeforamerica/ohana-api#303]
I cannot figure this out at all. The routes for [`/api`](https://ohana-test1.herokuapp.com/api) and [`/admin`](https://ohana-test1.herokuapp.com/admin) are completely missing after the app is deployed to Heroku with app.json. The `ENV` values that these routes depend on are all there. I tried to reproduce this locally and failed. I tried deploying the same app from CLI and couldn't reproduce it then either, even though the ENV values are exact the same. So I don't know what makes these routes disappear all of a sudden.

**Comment by monfresh** [comment]
This should be a comment in your PR, not an issue, since it's related to your PR, and not to existing code. I'm closing this issue and will respond in your PR.
