### ISSUE TITLE
Documentation for Adding Services

### ISSUE THREAD

**Issue by devinbalkind** [codeforamerica/ohana-api#305]
Hi.  I've written a step by step guide for adding services to Ohana using the admin/backend.  I did this for my users who need to perform these tasks.  I've found this process to be quite time consuming and am wondering if I'm missing something about how to use the app.  Please let me know if you think my process could be improved. Thanks.

1. Go to add location
type in organization name to see if organization exists
if does not exist, go to add new organization
if it does exist, skip to add a new location
2. Add new organization
add required: name description
click back to home
3. Add new location
required: select organization, location name, description, street address
click Add Street Address button
required: street address, city, state, country code (US)
save
4. Now you have to find the location you just entered to add a service to it… Go to the front end application.
5. Search for the name of the organization that manages the location
6. Click on the location you just created
7. Scroll down and click “Edit”. Now we're back in the admin area.
8. Scroll all the way down to "Add New Service"
required: name, description, how to apply
we also recommend adding service categories
click “Save”
9. You're back on the location page. Scroll down to Add New contact
required: name and other info

Here are a few changes that I think could improve the workflow:
* When creating a New Organization, give the user an autocomplete style display so they can see if that organization already exists. 
* After adding a new location, instead of bringing the user to /admin/locations bring them back to the page of the location they just created.  That way they they can add a service more easily.
* Add Search to the backend for organizations, services, locations, programs

That's just a few.  More to come as I use the application more.

Thanks for everything!

**Comment by monfresh** [comment]
Thanks, @devinbalkind. This is excellent feedback.

> After adding a new location, instead of bringing the user to /admin/locations bring them back to the page of the location they just created. That way they they can add a service more easily.

Makes sense. This is an easy fix.

> Add Search to the backend for organizations, services, locations, programs

This has been on my to-do list for future enhancements.

> When creating a New Organization, give the user an autocomplete style display so they can see if that organization already exists.

This shouldn't be necessary once search is in place. In the meantime, I believe organizations and locations are listed alphabetically by name, so you can find them that way. If they're not sorted alphabetically, that's an easy fix as well.

> Now you have to find the location you just entered to add a service to it… Go to the front end application.
Search for the name of the organization that manages the location
Click on the location you just created
Scroll down and click “Edit”. Now we're back in the admin area.

That is very interesting that you did that. What prompted you to do that? When you created the new location, it took you back to `/admin/locations`, right? Why couldn't you just click on the new location from `admin/locations`?

**Comment by monfresh** [comment]
I just fixed the redirect issue. After you create a new location, it will take you to that location.

**Comment by devinbalkind** [comment]
On Tue, Feb 17, 2015 at 6:45 PM, Moncef Belyamani <notifications@github.com>
wrote:

> Thanks, @devinbalkind <https://github.com/devinbalkind>. This is
> excellent feedback.
>

Happy you think so. :)

>  After adding a new location, instead of bringing the user to
> /admin/locations bring them back to the page of the location they just
> created. That way they they can add a service more easily.
>
> Makes sense. This is an easy fix.
>
> Add Search to the backend for organizations, services, locations, programs
>
> This has been on my to-do list for future enhancements.
>
> When creating a New Organization, give the user an autocomplete style
> display so they can see if that organization already exists.
>
> This shouldn't be necessary once search is in place. In the meantime, I
> believe organizations and locations are listed alphabetically by name, so
> you can find them that way. If they're not sorted alphabetically, that's an
> easy fix as well.
>

Organization and locations aren't sorted alphabetically in my
installation.  That would definitely be helpful.


>  Now you have to find the location you just entered to add a service to
> it… Go to the front end application.
> Search for the name of the organization that manages the location
> Click on the location you just created
> Scroll down and click “Edit”. Now we're back in the admin area.
>
> That is very interesting that you did that. What prompted you to do that?
> When you created the new location, it took you back to /admin/locations,
> right? Why couldn't you just click on the new location from
> admin/locations?
>

It's much easier for me to use the front end search interface than the
backend browse one.  Alphabetical ordering would help.  It would be even
more helpful if, instead of numbered pagination on the bottom it was
alphabetically organized as well.  Also, having a list of "recently
changed" items would somewhere would also facilitate a quicker workflow.

**Comment by monfresh** [comment]
Thanks, that's good info. I just pushed a fix to sort all entities alphabetically. I hope that helps while I work on search.

**Comment by monfresh** [comment]
I'm going to close this and open 2 new issues: one for admin search, and one for a list of recently changed items.

**Comment by devinbalkind** [comment]
Awesome.  Thanks.
