### ISSUE TITLE
Location Website does not transfer to Service

### ISSUE THREAD

**Issue by gl2748** [codeforamerica/ohana-api#307]
I can see why the general 'separation of powers' ... keeping Organization -> Location -> Service apart makes sense ... i.e. multiple locations and services can exist under one organization...however it is confusing to add info to a location and not have it appear on the service ... for example a location's website is not the service website by default...surely the most common use-case is for a single organization with a single location and a single service?

**Comment by monfresh** [comment]
Hi @gl2748. Thanks for using Ohana API!

If the Service website is the same as the Location website, the assumption is that there should not be a need to repeat it. When you perform a search, the API returns Locations, and when you query a particular Location, the API returns all of the Location's attributes (including the website), as well as all of the attributes of all of its Services, and all attributes for the Organization it belongs to.

In a client application like Ohana Web Search, when you view the details for a Location that has a website, its website is listed, and if the Service does not have its own unique URL, then the assumption is that the location's website has all the information about the Service. For example: http://ohana-web-search-demo.herokuapp.com/locations/samaritan-house/san-mateo-free-medical-clinic

The `website` attribute is not required, so it's OK for it to be blank if it's not different from the Location website. Moreover, even if it's a single organization with a single location and a single service, it's very possible that the service description could be in a different web page than the Location's homepage URL. In that case, you would enter a unique URL for the Service. For example: http://ohana-web-search-demo.herokuapp.com/locations/example-agency/example-location

In your case, what is the value of duplicating the website on the Service if it's the same as the Location's website?

**Comment by monfresh** [comment]
Closing this since I haven't heard back. Feel free to continue the discussion here though.
