### ISSUE TITLE
Support internationalized installations of Ohana

### ISSUE THREAD

**Issue by pmackay** [codeforamerica/ohana-api#319]
I'd like to understand what are the current thoughts on making Ohana more suitable for installation in other countries. Could the validations be made more configurable to support different locales? I'm not currently sure what other kinds of changes would be involved, just starting a conversation at this point.

Some examples:
* `ZipValidator` regex is for US zip codes.
* `state_province` is validated to be 2 characters long.
* UI strings related to these fields are not localizable.

Specifically the validators prevented importing of UK addresses when I was trying this.

**Comment by monfresh** [comment]
Thanks, Paul. Ideally, a GitHub issue (whether it's a bug report or a feature request) should contain the following details:

- What you did or were trying to do
- How you did it
- What you expected to happen
- What actually happened

In this case, I would ask you which specific validations failed for you, and what else makes Ohana unsuitable for installation in other countries.

**Comment by pmackay** [comment]
Have updated description with more details.

**Comment by monfresh** [comment]
Thanks for the update. For zip code validation, I think using one of [these gems](http://stackoverflow.com/questions/9793788/rails-conditional-validation-of-zip-code-for-many-countries) would be the best solution.

For `state_province` validation, I'm not sure if a gem exists, so it might make more sense to just update the documentation and show people how to disable or edit it.

And for the UI strings, did you mean the error messages related to the validation or something else? The error messages are localizable in [config/locales/en.yml](https://github.com/codeforamerica/ohana-api/blob/master/config/locales/en.yml). If you find any strings that should be localized, feel free to submit a PR.

**Comment by pmackay** [comment]
Thanks. Sounds like its better to submit very specific issues, which I can do for things related to this. But about this:

> it might make more sense to just update the documentation and show people how to disable or edit it.

Is there a long term interest in making this project easily deployable in other locales? If so, I wonder if a longer term solution would be needed to make this configurable, rather than a documented edit. This is what I'm trying to get a sense of from this issue at a general level.

**Comment by md5** [comment]
@pmackay You may be interested in the discussion I started around making `ohana-web-search` into a Rails Engine: https://github.com/codeforamerica/ohana-web-search/issues/798

I think most of what I said over there applies to `ohana-api` as well.

**Comment by monfresh** [comment]
@pmackay Yes, there is, but it depends on your definition of easy, and if there are other issues besides address validations.

What I had in mind for the `postal_code` and `state_province` validations was to tie them to a setting in `config/settings.yml` where you would define the locale, and the validations would automatically perform the appropriate work for the locale. For the `state_province` validation, that would mean adding a condition that the validation would only be performed if the locale was `US`. That would solve the issue with importing UK addresses.

However, if you wanted to validate that the `state_province` met certain conditions, you would have to add your own custom Rails validation. I'm all for making things as easy to customize as possible, but certain things aren't easily customizable from `settings.yml` or `application.yml`, and for certain levels of customization, you're gonna have to get into the code. Do you agree?

**Comment by pmackay** [comment]
@monfresh yes ok that's exactly the kind of info I was looking for. Totally agree with config via `settings.yml`. And yes validating states for different locales would need a new custom validator.

Happy to close this as its helped my understanding and best to raise focussed issues for each change. 

@md5 thanks for mention, very interesting thread but perhaps slightly different. Here I was trying to clarify what scope of changes could be pushed back upstream as it were, related to i18n.

**Comment by monfresh** [comment]
Sounds good. If you prefer to open separate focused issues, that's fine with me. Also, let me know if you were planning on submitting pull requests for those issues. If so, I would go with the [going_postal](https://github.com/globaldev/going_postal) gem for now because it also provides formatting options based on the country code.

**Comment by monfresh** [comment]
I'm closing now that we have separate issues. I also already fixed the state_province issue in #321.
