### ISSUE TITLE
wiki page change has broken some links

### ISSUE THREAD

**Issue by pmackay** [codeforamerica/ohana-api#330]
This page https://github.com/codeforamerica/ohana-api/wiki/Populating-the-Postgres-database-from-the-Human-Services-Data-Specification-%28HSDS%29-compliant-CSV-files has I think been renamed from https://github.com/codeforamerica/ohana-api/wiki/Populating-the-Postgres-database-from-OpenReferral-compliant-CSV-files which now doesnt exist. There are links on these pages to that old link that are broken:

* https://github.com/codeforamerica/ohana-api/wiki
* https://github.com/codeforamerica/ohana-api/blob/master/INSTALL.md

cc @RebeccaCoelius

**Comment by monfresh** [comment]
Thanks for the report. Feel free to submit a PR :smile:

**Comment by pmackay** [comment]
Done :) Actually realised its even easier than I thought to do PRs for text files. Fixed wiki page too.

**Comment by monfresh** [comment]
Closed via #331
