### ISSUE TITLE
Geocoder::OverQueryLimitError while importing locations, addresses

### ISSUE THREAD

**Issue by pmackay** [codeforamerica/ohana-api#336]
I'm raising this because I've already inserted all the lat/long values into the data, so that geocoding would not be needed. Is there a case where it would be triggered even if the lat/long are present?

**Comment by monfresh** [comment]
Thanks for the report! I fixed this issue, along with the invalid vs valid entries issue you reported in the other closed issue.

**Comment by pmackay** [comment]
Tested this, seems better, thanks!
