### ISSUE TITLE
Add instructions for logging into Admin interface after having populated the database

### ISSUE THREAD

**Issue by amsorribes** [codeforamerica/ohana-api#340]
After following the instructions on [Running Ohana API on your computer](https://github.com/codeforamerica/ohana-api/blob/master/INSTALL.md) and successfully [exporting](https://github.com/codeforamerica/ohana-api/blob/master/INSTALL.md#export-the-database) and [importing](https://github.com/codeforamerica/ohana-api/blob/master/INSTALL.md#import-the-database-locally) the database, it seems like the temporary users for the developer portal and admin interface defined in [db/seeds.rb](https://github.com/codeforamerica/ohana-api/blob/master/db/seeds.rb) are deleted, since they no longer work for login.

I tried following the instructions for setting a [Super User](https://github.com/codeforamerica/ohana-api/blob/master/INSTALL.md#user-and-admin-authentication-for-the-developer-portal-and-admin-interface), but my email does (quite obviously) not exists. However, I tried signing up from the admin interface (running on localhost) but that doesn't work either, I never get a confirmation email.

Please add instructions on how to add admins to the Ohana API after having populated the database, for local testing.
Thank you for a great project!

**Comment by monfresh** [comment]
Hi Amanda. As mentioned in the exporting section, `This will also automatically remove all test users and admins before the export.` When you run `script/export_prod_db`, the console output also lets you know it is `Removing test users and admins`. 

Exporting is usually meant to be done once you are ready to deploy to Heroku, and at that point, you would be creating real users in your production environment.

If you want to add the test users and admins back in your development database, you can run `script/users`. I updated the installation section with a note about adding these users back.

Real email delivery is turned off in development mode, so you will never actually receive a real email. Instead, we use the [letter_opener](https://github.com/ryanb/letter_opener) gem that lets you preview and test emails in the browser. If you were running the app directly on your computer as opposed to inside Vagrant, you would see a new browser tab open with the confirmation email, and you could click on the link in that email.

The [letter_opener_web](https://github.com/fgrehm/letter_opener_web) gem allows you to see emails in the browser when running in Vagrant, but it's not included in this app yet, and it requires you to manually visit a particular URL. It doesn't automatically open the email in the browser.

In the meantime, what you can do is view the email in your command line app's log. When you run the app with `rails s -p 8080 -b 0.0.0.0`, you will see the actual email in the log when you sign up for an admin account. Then, you can copy and paste the confirmation link from the log into your browser.

**Comment by amsorribes** [comment]
Hi Moncef, thank you for your response. 

Although I feel I have started to get the grasp of how the different components work and interact, the issue about the users of the admin interface is what still eludes me - not from an individual user's point of view - but as the administrator of the site, once the database has been populated (by me) and has been deployed. How do I add myself as a super user? How do I add other people (their e-mails) as administrators of organizations that already exist in the database?

Hope you can help me solve this, thanks again!

**Comment by monfresh** [comment]
Please read our Wiki article: https://github.com/codeforamerica/ohana-api/wiki/Admin-interface-basics

**Comment by amsorribes** [comment]
Okay, thank you. Obviously I had already read that document too, although the solution was in the INSTALL.rd after all. With all the trouble I was having with getting the admin users to work locally, I missed that last part on how to do it on Heroku. That solved it, thank you for pointing me in the right direction.

**Comment by monfresh** [comment]
No problem. The Wiki points to `INSTALL.md` so that if the instructions change for some reason, we only need to update them in one place. Also, I just added the Heroku section earlier today, so it wasn't your fault for missing it :smile:
