### ISSUE TITLE
Service name doesn't seem to be included in search index

### ISSUE THREAD

**Issue by monfresh** [codeforamerica/ohana-api#364]
One of the service names in the example data is "Passport Photos", but when I search for `keyword=passport`, or even `keyword=Passport Photos`, no results show up. Looking at the `tsv_body` column for the example location, I don't see the words `passport` or `photos`. The SQL for the other service attributes, such as `description`, seems to be the same as the one for `name`, so I'm not sure what's going on.

**Comment by monfresh** [comment]
I think `description` is not being included either. My guess is that those fields require `string_agg` like the categories and keywords, which do work.

**Comment by cderenburger** [comment]
Is alternate_name supposed to be searchable as well?  I removed it from my import but I'm sure it was displayed in search results for the organization, but the alternate_name was not searchable by keyword or organization name.

**Comment by monfresh** [comment]
I can't reproduce this. I think it might have been of the way the DB was populated on the demo website. After I saved the example service (thereby triggering the full text search index to update), I was able to get results that match both the service name and description. I also wrote tests for this in the code and they passed.
