### ISSUE TITLE
Consider switching to SendGrid instead of Mandrill

### ISSUE THREAD

**Issue by marks** [codeforamerica/ohana-api#372]
it's free

**Comment by monfresh** [comment]
Thanks for the heads up. Mandrill used to offer a free plan as well, but it looks like they dropped it from Heroku. Feel like submitting a PR?

**Comment by marks** [comment]
Will try to yes. Switching to send grid was rather simple so far 


--
Mark Silverberg
(m) 512 826 7004
http://twitter.com/skram
