### ISSUE TITLE
Would like a search field on Location and Organization pages

### ISSUE THREAD

**Issue by kelfink** [codeforamerica/ohana-api#378]
Seems like this is partially implemented (Search concern), and I'm looking at implementing it on our branch.  There should be an input field on the admin pages to allow searching the entities for matches, so we can avoid wading through 50+ pages of locations or organizations.

**Comment by monfresh** [comment]
Yes, I agree search would be helpful in the admin interface. We already have an open issue for this (https://github.com/codeforamerica/ohana-api/issues/312) so I'm closing this one as a duplicate. Pull requests are welcome, so if you implement this on your branch, feel free to send a pull request.
